import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/NavBar";
import ButtonTheme from "../components/ButtonTheme";
import { ThemeProvider } from "../context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <NavBar />
          {children}
          <ButtonTheme className="fixed bottom-4 right-4 z-50" />
        </ThemeProvider>
      </body>
    </html>
  );
}
